### ISSUE TITLE
Failing tests on master

### ISSUE THREAD

**Issue by pixelass** [tur-nr/polymer-redux#118]
# Failing tests

## Actual behavior

When running `npm test` the following error occurs (see log)

## Expected behavior 

Test should pass

## Log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'lint' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle polymer-redux@1.0.4~prelint: polymer-redux@1.0.4
6 info lifecycle polymer-redux@1.0.4~lint: polymer-redux@1.0.4
7 verbose lifecycle polymer-redux@1.0.4~lint: unsafe-perm in lifecycle true
8 verbose lifecycle polymer-redux@1.0.4~lint: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/greada/Documents/workspace/github/polymer-redux/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/greada/Documents/workspace/github/polymer-redux/node_modules/.bin:/Users/greada/.jenv/bin:/Users/greada/.jenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle polymer-redux@1.0.4~lint: CWD: /Users/greada/Documents/workspace/github/polymer-redux
10 silly lifecycle polymer-redux@1.0.4~lint: Args: [ '-c', 'xo && polymer lint --root=$(pwd)/lib' ]
11 silly lifecycle polymer-redux@1.0.4~lint: Returned: code: 1  signal: null
12 info lifecycle polymer-redux@1.0.4~lint: Failed to exec lint script
13 verbose stack Error: polymer-redux@1.0.4 lint: `xo && polymer lint --root=$(pwd)/lib`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid polymer-redux@1.0.4
15 verbose cwd /Users/greada/Documents/workspace/github/polymer-redux
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error polymer-redux@1.0.4 lint: `xo && polymer lint --root=$(pwd)/lib`
22 error Exit status 1
23 error Failed at the polymer-redux@1.0.4 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pixelass** [comment]
@tur-nr any idea on this? Maybe I can fix this for you. I just don't fully understand the origin of the issue. 

Help wanted!

**Comment by tur-nr** [comment]
Tests are working fine on master.
